version: 2

sources:
  - name: raw
    database: "{{ var('raw_database', 'RAW_DEV') }}"
    schema: events
    description: "Raw tables for events data"
    config:
      freshness:
        warn_after:  {count: 48, period: hour}
        error_after: {count: 72, period: hour}
      loaded_at_field: _loaded_at

    tables:
      - name: marketing_clicks
        description: "Raw marketing clicks records"
